title: "Destination Earth Notebook Gallery"
author: "Katharina Starzer"
description: "Notebook Gallery für Destination Earth - Automatische Integration von Repositories."
execute:
  execute_notebooks: cache