name: New Notebook Submission
description: Issue Template for submitting a new notebook to the gallery
title: "[New Notebook] <Notebook Title>"
labels: submission, pending-review
assignees: katharinastarzer21

body:
  - type: input
    id: notebook-name
    attributes:
      label: Notebook Name
      placeholder: Your notebook name here
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Brief description of your notebook
