name: "Cookbook Production Build"

on:
  issues:
    types: [closed]

jobs:
  deploy:
    if: github.event.issue.user.login == 'katharinastarzer21'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DestinE repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Save issue body to file
        run: echo "${{ github.event.issue.body }}" > issue_body.txt

      - name: Install required packages
        run: |
          pip install -r templates/requirements.txt
          pip install pyyaml 

      - name: Parse Issue Data
        id: parse
        run: |
          python scripts/parse_issue.py 

      - name: Import Cookbook
        run: |
          python scripts/import_cookbook.py --repo_url "$REPO_URL" --root_path "$ROOT_PATH"
        env:
          REPO_URL: ${{ env.REPO_URL }}
          ROOT_PATH: ${{ env.ROOT_PATH }}

      - name: Install Sphinx build dependencies
        run: |
          pip install -r templates/requirements.txt

      - name: Copy default conf.py/reqs if missing
        run: |
          python scripts/ensure_defaults.py --cookbook_dir "./cookbooks/${{ steps.parse.outputs.root_path }}"

      - name: Build Sphinx site
        working-directory: cookbooks/${{ env.ROOT_PATH }}
        run: |
          sphinx-build . _build/html

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Load existing gallery YAML from gh-pages
        run: |
          if [ -f gallery/notebook_gallery.yaml ]; then
            echo "✅ Existing gallery found"
          else
            mkdir -p gallery
            echo "domains: {}" > gallery/notebook_gallery.yaml
          fi

      - name: Update gallery YAML (production)
        run: |
          python scripts/update_gallery.py --cookbook_dir "./cookbooks/${{ steps.parse.outputs.root_path }}" --mode production

      - name: Copy index.md from main/docs to gallery/
        run: |
          git checkout origin/main -- docs/index.md
          mkdir -p gallery
          cp docs/index.md gallery/index.md

      - name: Generate updated index.md
        run: |
          python scripts/update_index.py

      - name: Commit and push updated gallery to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add gallery/index.md gallery/notebook_gallery.yaml
          git commit -m "Update gallery after adding ${{ env.ROOT_PATH }}" || echo "No changes"
          git push origin gh-pages

