name: "Cookbook Production Build"

on:
  issues:
    types: [closed]

jobs:
  deploy:
    if: github.event.issue.user.login == 'katharinastarzer21'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DestinE repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Save issue body to file
        run: echo "${{ github.event.issue.body }}" > issue_body.txt

      - name: Install required packages
        run: |
          pip install -r templates/requirements.txt
          pip install pyyaml 

      - name: Parse Issue Data
        id: parse
        run: |
          python scripts/parse_issue.py 

      - name: Import Cookbook
        run: |
          python scripts/import_cookbook.py --repo_url "$REPO_URL" --root_path "$ROOT_PATH"
        env:
          REPO_URL: ${{ env.REPO_URL }}
          ROOT_PATH: ${{ env.ROOT_PATH }}

      - name: Install Sphinx build dependencies
        run: |
          pip install -r templates/requirements.txt

      - name: Copy default conf.py/reqs if missing
        run: |
          python scripts/ensure_defaults.py --cookbook_dir "./cookbooks/${{ steps.parse.outputs.root_path }}"

      - name: Build Sphinx site
        working-directory: cookbooks/${{ env.ROOT_PATH }}
        run: |
          sphinx-build . _build/html

      - name: Deploy to GitHub Pages (production)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cookbooks/${{ steps.parse.outputs.root_path }}/_build/html
          destination_dir: production/${{ steps.parse.outputs.root_path }}

      - name: Update gallery YAML (production)
        run: |
          python scripts/update_gallery.py --cookbook_dir "./cookbooks/${{ steps.parse.outputs.root_path }}" --mode production