name: Integrate Repository

on:
  issues:
    types: [opened, labeled]

jobs:
  integrate:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'pending-review')

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        environment-file: environment.yml
        activate-environment: dedl-notebook-dev

    - name: Install Dependencies (Fallback)
      run: |
        pip install jupyter-book matplotlib numpy jq

    - name: Fetch Issue Data
      run: |
        echo "${{ toJson(github.event) }}" > event.json
        cat event.json

    - name: Extract Repository URL
      id: extract
      run: |
          echo "Issue Body Content:"
          echo "${{ github.event.issue.body }}"
          
          repo_url=$(echo "${{ github.event.issue.body }}" | grep -o 'https://github.com/[^ ]*')
          
          echo "Extracted URL: $repo_url"
          echo "::set-output name=repo_url::$repo_url"

    - name: Clone Submitted Repository
      run: |
        git clone ${{ steps.extract.outputs.repo_url }} new_repo
        ls new_repo

    - name: Find Notebooks in Submitted Repository
      id: find_notebooks
      run: |
        find new_repo -name "*.ipynb" > notebooks_list.txt
        cat notebooks_list.txt
        echo "::set-output name=notebooks::$(cat notebooks_list.txt)"
      
    - name: Update _toc.yml
      run: |
        echo "format: jb-book" > _toc.yml
        echo "root: README" >> _toc.yml
        echo "" >> _toc.yml
        echo "chapters:" >> _toc.yml

        notebooks=$(cat notebooks_list.txt)
        IFS=$'\n'
        for notebook in $notebooks; do
          # Entferne den 'new_repo/' Prefix und die Dateiendung '.ipynb'
          notebook_path=$(echo "$notebook" | sed 's|new_repo/||' | sed 's|.ipynb||')
          echo "  - file: ${notebook_path}" >> _toc.yml
        done
        cat _toc.yml

    - name: Build the Book
      run: |
        jupyter-book build .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
        publish_branch: gh-pages
