name: Integrate Repository

on:
  issues:
    types: [opened, labeled]

jobs:
  integrate:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'pending-review')

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book

    - name: Install jq
      run: sudo apt-get install jq

    - name: Fetch Issue Data
      run: echo "${{ toJson(github.event) }}" > event.json

    - name: Extract Repository URL
      id: extract
      run: |
        repo_url=$(cat event.json | jq -r '.issue.body' | grep -o 'https://github.com/[^ ]*')
        echo "Repository URL: $repo_url"
        echo "::set-output name=repo_url::$repo_url"

    - name: Clone Submitted Repository
      run: |
        git clone ${{ steps.extract.outputs.repo_url }} new_repo
        ls new_repo

    - name: Update _toc.yml
      run: |
        echo "- file: new_repo/README" >> _toc.yml

    - name: Build the Book
      run: |
        jupyter-book build .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
        publish_branch: gh-pages
