name: Preview New Cookbook Submission

on:
  issues:
    types: [opened]

jobs:
  preview-cookbook:
    if: contains(github.event.issue.labels.*.name, 'add-repo')
    runs-on: ubuntu-latest

    env:
      PREVIEW_PATH: previews/${{ github.event.issue.number }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install required packages
        run: |
          pip install -r requirements.txt
          pip install pyyaml

      - name: Save issue body to file
        run: echo "${{ github.event.issue.body }}" > issue_body.txt

      - name: Parse issue and extract info
        run: python parse_issue.py --preview
        env:
          GITHUB_ENV: ${{ github.env }}

      - name: Clone submitted repository
        run: git clone $REPO_URL submitted_repo

      - name: Prepare submitted repo
        run: |
          if [ -f submitted_repo/README.md ] && [ ! -f submitted_repo/index.md ]; then
            cp submitted_repo/README.md submitted_repo/index.md
          fi

      - name: Build preview with Sphinx
        run: |
          sphinx-build -b html submitted_repo ../_preview_output -c docs

      - name: Publish to gh-pages
        run: |
          git fetch origin gh-pages
          git clean -fdx
          git checkout gh-pages
          git pull

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          rm -rf previews/${{ github.event.issue.number }}
          mkdir -p previews/${{ github.event.issue.number }}
          cp -r ../_preview_output/* previews/${{ github.event.issue.number }}/

          git add previews/${{ github.event.issue.number }}/
          git commit -m "Preview für Issue #${{ github.event.issue.number }}" || echo "No changes"
          git push origin gh-pages

      - name: Comment with preview link
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |

            🔗 https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/previews/${{ github.event.issue.number }}/index.html
