name: "Cookbook Preview Build"

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:

jobs:
  preview:
    if: github.event.label.name == 'add-repo' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DestinE repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requirements for scripts
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML requests

      - name: Save issue body to file
        run: echo "${{ github.event.issue.body }}" > issue_body.txt

      - name: Parse Issue Data
        id: parse
        run: |
          python scripts/parse_issue.py --issue_number ${{ github.event.issue.number }} --github_token ${{ secrets.GITHUB_TOKEN }}

      - name: Clone Cookbook Repo
        run: |
          python scripts/import_cookbook.py --repo_url "${{ steps.parse.outputs.repo_url }}" --root_path "${{ steps.parse.outputs.root_path }}"

      - name: Install Sphinx build dependencies
        run: |
          pip install -r templates/requirements.txt

      - name: Copy default conf.py/reqs if missing
        run: |
          python scripts/ensure_defaults.py --cookbook_dir "./cookbooks/${{ steps.parse.outputs.root_path }}"

      - name: Build Sphinx site
        working-directory: cookbooks/${{ steps.parse.outputs.root_path }}
        run: |
          sphinx-build . _build/html

      - name: Deploy Preview to GitHub Pages (staging)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cookbooks/${{ steps.parse.outputs.root_path }}/_build/html
          destination_dir: preview/${{ steps.parse.outputs.root_path }}

      - name: Update gallery YAML (preview)
        run: |
          python scripts/update_gallery.py --cookbook_dir "./cookbooks/${{ steps.parse.outputs.root_path }}" --mode preview