name: Preview New Cookbook

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  preview-cookbook:
    if: github.event.label.name == 'add-repo' || contains(github.event.issue.labels.*.name, 'add-repo')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v4
      
      - name: Install required packages
        run: |
          pip install -r templates/requirements.txt
          pip install pyyaml

      - name: Save issue body to file
        run: echo "${{ github.event.issue.body }}" > issue_body.txt

      - name: Parse Issue Data
        id: parse
        run: |
          python scripts/parse_issue.py --preview

      - name: Debug parsed env vars
        run: |
          echo "REPO_URL=$REPO_URL"
          echo "ROOT_PATH=$ROOT_PATH"

      - name: Import Cookbook
        run: |
          python scripts/import_cookbook.py --repo_url "$REPO_URL" --root_path "$ROOT_PATH"

      - name: Build Sphinx documentation
        run: |
          sphinx-build cookbooks/$ROOT_PATH cookbooks/$ROOT_PATH/_build/html

