name: Update Notebook Gallery

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book

    - name: Build the book
      run: |
        jupyter-book build .

    - name: Check if build directory exists
      run: |
        if [ -d "_build/html" ]; then echo "Build directory exists."; else echo "Build directory does NOT exist."; fi

    - name: Upload HTML files as artifact
      if: success() && always()  # Ensures that the upload only happens if the build step was successful
      uses: actions/upload-artifact@v2
      with:
        name: html-site
        path: _build/html
